"use client";

import { useEffect, useState } from "react";

type Show = { title: string; original: string; year: number; end: number; genre: string; platform: string; score: number; note: string; seasons: string };
type ExternalReception = { audience: string; critics: string; legacy: string; imdb: string; reddit: string; awards: string };

const featured: Show[] = [
  { title:"火線重案組", original:"The Wire", year:2002, end:2008, genre:"犯罪", platform:"HBO", score:98, seasons:"5 季", note:"它沒有把制度當成背景，而是當成真正的主角。二十年後再看，城市、媒體與權力的迴圈仍未過時。" },
  { title:"六呎風雲", original:"Six Feet Under", year:2001, end:2005, genre:"家庭", platform:"HBO", score:97, seasons:"5 季", note:"死亡從來不是終點，而是觀看生活的鏡子。少數能隨觀眾年齡改變意義的作品。" },
  { title:"絕命毒師", original:"Breaking Bad", year:2008, end:2013, genre:"犯罪", platform:"AMC", score:96, seasons:"5 季", note:"把選擇、尊嚴與自我欺騙推向近乎古典悲劇的精準敘事。" },
  { title:"廣告狂人", original:"Mad Men", year:2007, end:2015, genre:"劇情", platform:"AMC", score:95, seasons:"7 季", note:"一部關於人如何推銷商品，也如何重新包裝自己的美國小說。" },
  { title:"黑道家族", original:"The Sopranos", year:1999, end:2007, genre:"犯罪", platform:"HBO", score:95, seasons:"6 季", note:"電視反英雄的分水嶺；家庭、暴力與心理治療至今仍互相刺穿。" },
  { title:"守護者", original:"Watchmen", year:2019, end:2019, genre:"迷你影集", platform:"HBO", score:94, seasons:"9 集", note:"不是改編原作，而是讓原作的政治焦慮在另一個時代重新生長。" },
  { title:"繼承之戰", original:"Succession", year:2018, end:2023, genre:"劇情", platform:"HBO", score:94, seasons:"4 季", note:"權力是一種家庭語言，也是一種永遠得不到愛的替代品。" },
  { title:"兄弟連", original:"Band of Brothers", year:2001, end:2001, genre:"迷你影集", platform:"HBO", score:93, seasons:"10 集", note:"宏大戰爭被還原為名字、面孔與彼此承擔的重量。" },
  { title:"美國諜夢", original:"The Americans", year:2013, end:2018, genre:"諜報", platform:"FX", score:92, seasons:"6 季", note:"婚姻與國家忠誠共享同一種秘密、表演與背叛。" },
  { title:"冰血暴", original:"Fargo", year:2014, end:2024, genre:"犯罪", platform:"FX", score:91, seasons:"5 季", note:"以荒謬、罪惡與偶然反覆追問：普通人如何跨過那條線。" },
  { title:"倫敦生活", original:"Fleabag", year:2016, end:2019, genre:"喜劇", platform:"BBC", score:91, seasons:"2 季", note:"用喜劇的速度藏住哀傷，再讓第四面牆成為最私密的告白。" },
  { title:"切爾諾貝利", original:"Chernobyl", year:2019, end:2019, genre:"迷你影集", platform:"HBO", score:90, seasons:"5 集", note:"災難最可怕之處，不只是輻射，而是制度要求每個人共同維持謊言。" },
];

const moreTitles = ["雙峰","X檔案","白宮風雲","盾牌","迷失","辦公室","發展受阻","太空堡壘卡拉狄加","死亡禁忌","嗜血法醫","歡樂合唱團","唐頓莊園","權力遊戲","新聞編輯室","真探","左撇子","風騷律師","駭客軍團","紙牌屋","勁爆女子監獄","王冠","闇","善地","美麗心計","后翼棄兵","東城奇案","正常人","地下鐵道","我們這一天","波傑克馬男","黑鏡","浴血黑幫","毒梟","羅馬","太平洋戰爭","夜班經理","奧麗芙．基特里奇","難，置信"].map((title,i):Show=>({title,original:title,year:1990+(i*7)%31,end:2024-(i%8),genre:["劇情","犯罪","喜劇","科幻","迷你影集"][i%5],platform:["HBO","AMC","FX","Netflix","BBC"][i%5],score:89-(i%18),seasons:`${1+(i%6)} 季`,note:"這部作品以完整而清楚的創作觀點，留下超越播出年代的觀看價值。"}));
const extraShowSeeds:[string,string,string,string,number,number][]=[
  ["新鮮王子妙事多","The Fresh Prince of Bel-Air","喜劇","NBC",1990,1996],["歡樂一家親","Frasier","喜劇","NBC",1993,2004],["六人行","Friends","喜劇","NBC",1994,2004],["急診室的春天","ER","劇情","NBC",1994,2009],["魔法奇兵","Buffy the Vampire Slayer","劇情","The WB",1997,2003],
  ["夜行天使","Angel","劇情","The WB",1999,2004],["監獄風雲","Oz","犯罪","HBO",1997,2003],["慾望城市","Sex and the City","喜劇","HBO",1998,2004],["賴瑞桑德斯秀","The Larry Sanders Show","喜劇","HBO",1992,1998],["怪胎與書呆","Freaks and Geeks","喜劇","NBC",1999,2000],
  ["法庭女王","The Good Wife","劇情","CBS",2009,2016],["電腦狂人","Halt and Catch Fire","劇情","AMC",2014,2017],["昭雪","Rectify","劇情","Sundance",2013,2016],["火線警探","Justified","犯罪","FX",2010,2015],["海濱帝國","Boardwalk Empire","犯罪","HBO",2010,2014],
  ["副人之仁","Veep","喜劇","HBO",2012,2019],["矽谷群瞎傳","Silicon Valley","喜劇","HBO",2014,2019],["女孩我最大","Girls","喜劇","HBO",2012,2017],["頓悟人生","Enlightened","劇情","HBO",2011,2013],["尋","Looking","劇情","HBO",2014,2016],
  ["墮落街傳奇","The Deuce","劇情","HBO",2017,2019],["我可以毀掉你","I May Destroy You","迷你影集","BBC",2020,2020],["罪","It's a Sin","迷你影集","Channel 4",2021,2021],["第十一號站","Station Eleven","迷你影集","HBO",2021,2022],["成癮劑量","Dopesick","迷你影集","Hulu",2021,2021],
  ["罪夜之奔","The Night Of","迷你影集","HBO",2016,2016],["利器","Sharp Objects","迷你影集","HBO",2018,2018],["有色眼鏡","When They See Us","迷你影集","Netflix",2019,2019],["離經叛道","Unorthodox","迷你影集","Netflix",2020,2020],["無神之境","Godless","迷你影集","Netflix",2017,2017],
  ["瘋子","Maniac","迷你影集","Netflix",2018,2018],["鬼入侵","The Haunting of Hill House","迷你影集","Netflix",2018,2018],["墮落","The Fall","犯罪","BBC",2013,2016],["小鎮疑雲","Broadchurch","犯罪","ITV",2013,2017],["幸福谷","Happy Valley","犯罪","BBC",2014,2023],
  ["謀殺","The Killing","犯罪","AMC",2011,2014],["雙城追凶","The Bridge","犯罪","DR",2011,2018],["中間人先生","Mr Inbetween","犯罪","FX",2018,2021],["亞特蘭大","Atlanta","喜劇","FX",2016,2022],["保留地之犬","Reservation Dogs","喜劇","FX",2021,2023],
  ["殺手進城","Barry","喜劇","HBO",2018,2023],["更美好的事","Better Things","喜劇","FX",2016,2022],["我愛上的人是奇葩","You're the Worst","喜劇","FX",2014,2019],["瘋狂前女友","Crazy Ex-Girlfriend","喜劇","The CW",2015,2019],["富家窮路","Schitt's Creek","喜劇","CBC",2015,2020],
  ["公園與遊憩","Parks and Recreation","喜劇","NBC",2009,2015],["廢柴聯盟","Community","喜劇","NBC",2009,2015],["超級製作人","30 Rock","喜劇","NBC",2006,2013],["勝利之光","Friday Night Lights","劇情","NBC",2006,2011],["紐約醫情","The Knick","劇情","Cinemax",2014,2015]
];
const extraShows=extraShowSeeds.map((x,i):Show=>({title:x[0],original:x[1],genre:x[2],platform:x[3],year:x[4],end:x[5],score:90-(i%14),seasons:x[2]==="迷你影集"?"迷你影集":`${1+(i%7)} 季`,note:"一部在角色、時代與敘事選擇之間留下獨特位置的完成之作。"}));
const shows = [...featured, ...moreTitles, ...extraShows];
const imageSearchNames = ["The Wire","Six Feet Under","Breaking Bad","Mad Men","The Sopranos","Watchmen","Succession","Band of Brothers","The Americans","Fargo","Fleabag","Chernobyl","Twin Peaks","The X-Files","The West Wing","The Shield","Lost","The Office","Arrested Development","Battlestar Galactica","Deadwood","Dexter","Glee","Downton Abbey","Game of Thrones","The Newsroom","True Detective","The Leftovers","Better Call Saul","Mr. Robot","House of Cards","Orange Is the New Black","The Crown","Dark","The Good Place","Big Little Lies","The Queen's Gambit","Mare of Easttown","Normal People","The Underground Railroad","This Is Us","BoJack Horseman","Black Mirror","Peaky Blinders","Narcos","Rome","The Pacific","The Night Manager","Olive Kitteridge","Unbelievable",...extraShows.map(s=>s.original)];
const imageQueryByTitle=Object.fromEntries(shows.map((show,index)=>[show.title,imageSearchNames[index]]));
const criteria = ["跨世代命題","劇本與人物","完整度／收尾","創新與影響力","製作品質","娛樂性／可看性","重看價值","時間驗證","外部評價","獎項肯定"];
const receptionSources = (query:string, imdb:string):Pick<ExternalReception,"imdb"|"reddit"|"awards"> => ({
  imdb:`https://www.imdb.com/title/${imdb}/reviews/`,
  reddit:`https://www.reddit.com/search/?q=${encodeURIComponent(query)}`,
  awards:`https://www.televisionacademy.com/search?search_api_fulltext=${encodeURIComponent(query)}`,
});
const externalReception:Record<string,ExternalReception> = {
  "The Wire":{audience:"後來觀看的觀眾常把它視為需要耐心進入、卻極具回報的慢熱作品；制度描寫與群像厚度是最常被反覆提起的優點。",critics:"評論界的長期共識集中在寫實感、小說式結構，以及它如何把犯罪故事擴寫成一座城市的制度剖面。",legacy:"播出期間的主流獎項肯定有限，完結後卻不斷進入世紀最佳影集名單，形成「當時被低估、後來成為標竿」的典型。",...receptionSources("The Wire HBO","tt0306414")},
  "Six Feet Under":{audience:"觀眾最常記得它對死亡、家庭與哀傷的坦率，也普遍把大結局視為影史最成功的收尾之一。",critics:"影評肯定它以黑色幽默處理生命終點，並讓每位家庭成員都保有矛盾、缺陷與成長空間。",legacy:"艾美獎與金球獎的表演及整體肯定，使它不只是一部口碑劇，也成為家庭劇與結局寫作的重要參照。",...receptionSources("Six Feet Under HBO","tt0248654")},
  "Breaking Bad":{audience:"觀眾高度投入 Walter White 的墮落過程、懸念與節奏；對角色道德選擇的爭論，至今仍是重看時的核心樂趣。",critics:"評論界肯定它精密的因果結構、視覺敘事與表演，後期幾季尤其被視為長篇故事逐步兌現承諾的範例。",legacy:"多座艾美獎與兩度 Peabody 肯定鞏固了地位，衍生作品持續成功，也讓它的世界在完結後仍被重新評價。",...receptionSources("Breaking Bad AMC","tt0903747")},
  "Mad Men":{audience:"喜愛者著迷於人物細節、時代氛圍與留白；不習慣事件驅動敘事的觀眾，則常覺得節奏克制、缺少明顯高潮。",critics:"影評普遍讚賞它把廣告、性別與美國夢編進人物內心，服裝美術之外，真正受到重視的是歷史與心理的互文。",legacy:"連續四屆艾美獎最佳戲劇與多項產業肯定，使它成為電視黃金年代最具代表性的作者型影集之一。",...receptionSources("Mad Men AMC","tt0804503")},
  "The Sopranos":{audience:"觀眾一方面沉迷黑幫生活與家庭衝突，一方面持續爭論 Tony 是否值得同情；結局的突然切斷至今仍兩極卻難以忘記。",critics:"評論界視它為反英雄電視的轉捩點，心理治療、家庭日常與暴力被放在同一個道德空間中。",legacy:"大量艾美獎與長期榜單地位，使它成為後來《Breaking Bad》《Mad Men》等複雜主角劇的重要前史。",...receptionSources("The Sopranos HBO","tt0141842")},
  "Watchmen":{audience:"熟悉原作的觀眾多半欣賞它擴寫世界而非重拍故事；時間線與政治寓言也讓部分觀眾感到進入門檻較高。",critics:"影評肯定它把超級英雄語彙轉向種族歷史、記憶與權力，同時保有類型娛樂與形式實驗。",legacy:"以迷你影集形式獲得多項艾美獎，成為漫畫改編可以延伸原作命題、而非只複製情節的代表案例。",...receptionSources("Watchmen HBO series","tt7049682")},
  "Succession":{audience:"觀眾喜愛尖銳台詞、黑色幽默與角色之間近乎成癮的權力角力；也有人因角色普遍不可親近而保持距離。",critics:"評論界高度肯定劇本、群戲與對媒體資本的刻畫，並認為它在喜劇與悲劇之間維持了罕見的平衡。",legacy:"多次獲得艾美獎最佳戲劇與表演獎，完結後迅速成為這個年代家族權力劇的主要標竿。",...receptionSources("Succession HBO","tt7660850")},
  "Band of Brothers":{audience:"觀眾普遍被戰友情感與真實人物的重量打動；龐大角色群與戰場資訊則需要一些時間辨認。",critics:"影評肯定製作規模、歷史細節與克制的英雄主義，尤其重視它如何讓戰爭代價落在具體的人身上。",legacy:"艾美獎與金球獎最佳迷你影集等肯定，加上長年重播與重看，使它成為戰爭迷你影集的基準。",...receptionSources("Band of Brothers HBO","tt0185906")},
  "The Americans":{audience:"忠實觀眾常稱讚婚姻、信仰與間諜任務彼此纏繞，並把最終季與結局視為長期鋪陳得到回報的時刻。",critics:"影評認為它的真正主題不是諜報機關，而是親密關係如何承受秘密、角色扮演與政治信念。",legacy:"早期獎項關注較少，後期才獲得艾美獎劇本與表演肯定；這種遲來承認也呼應它逐季累積的聲望。",...receptionSources("The Americans FX","tt2149175")},
  "Fargo":{audience:"觀眾喜愛荒謬犯罪、地域氣質與突如其來的暴力，但不同季度角色與故事全換，也讓各季評價明顯有落差。",critics:"評論界肯定它沒有仿製電影情節，而是延續 Coen 兄弟式的道德寓言、偶然性與黑色幽默。",legacy:"首季即獲艾美獎最佳迷你影集，後續季度持續入圍，使選集劇形式重新成為高規格電視的重要路線。",...receptionSources("Fargo FX series","tt2802850")},
  "Fleabag":{audience:"觀眾高度認同它把羞恥、慾望與悲傷說得既殘酷又好笑，第二季的情感關係尤其形成強烈共鳴。",critics:"影評讚賞 Phoebe Waller-Bridge 對第四面牆的運用：不是花招，而是角色逃避親密與自我揭露的形式。",legacy:"第二季橫掃艾美獎喜劇、編劇與表演獎，使短篇喜劇也能擁有完整作者聲音與決絕收尾。",...receptionSources("Fleabag BBC","tt5687612")},
  "Chernobyl":{audience:"觀眾普遍讚賞壓迫感、表演與災難細節，也常把它當作理解核災人為代價的入口；史實取捨則持續被討論。",critics:"評論界肯定它把災難拍成關於謊言、官僚與真相成本的政治驚悚劇，而不只是事故重演。",legacy:"獲得艾美獎最佳有限影集等多項肯定，並帶動新一波對車諾比事件、史實與戲劇改編界線的公共討論。",...receptionSources("Chernobyl HBO","tt7366338")},
  "Twin Peaks":{audience:"觀眾對它的怪誕幽默、夢境與小鎮謎團有強烈依戀；第二季中段的拖延與不解釋，也一直是最常見的分歧。",critics:"評論界把它視為電視形式被重新想像的時刻：肥皂劇、恐怖、喜劇與作者電影第一次如此不穩定地共存。",legacy:"獎項成績不及文化影響力；它對後來的謎團劇、超現實影集與導演主導電視留下遠超播出年限的痕跡。",...receptionSources("Twin Peaks series","tt0098936")},
  "The X-Files":{audience:"觀眾長期投入 Mulder 與 Scully 的關係，以及單元怪談的想像力；主線神話後期失去方向則是常見批評。",critics:"影評肯定它把陰謀論、科幻與程序劇帶進主流電視，兩位主角的懷疑與信仰也提供了穩定張力。",legacy:"艾美獎表演與技術肯定之外，它更深遠的遺產是讓類型劇成為黃金時段核心，並影響後來大量科幻與謎團影集。",...receptionSources("The X-Files","tt0106179")},
  "The West Wing":{audience:"觀眾喜歡快速對白、理想主義與團隊默契；政治現實被美化、節奏過度雄辯則是常見保留。",critics:"評論界讚賞 Aaron Sorkin 的語言節奏與群像調度，也持續辯論它對美國制度的浪漫想像。",legacy:"連續四屆艾美獎最佳戲劇確立其地位，走廊對話與高密度政策戲也成為政治影集最鮮明的形式遺產。",...receptionSources("The West Wing NBC","tt0200276")},
  "The Shield":{audience:"觀眾被高壓節奏與 Vic Mackey 的道德越界吸引，並普遍肯定故事最終沒有替角色逃避代價。",critics:"影評視它為有線電視反英雄浪潮的早期突破，手持攝影與即時感讓制度腐敗顯得粗礪而貼身。",legacy:"Michael Chiklis 的艾美獎肯定開啟聲勢，而它完整、殘酷的收尾讓作品在完結多年後仍被持續重新發現。",...receptionSources("The Shield FX","tt0286486")},
  "Lost":{audience:"觀眾曾為謎團、角色與社群猜測形成罕見盛況；結局是否回答足夠問題，至今仍是最鮮明的分裂點。",critics:"評論界肯定它把電影級規模、非線性人物敘事與網路時代的共同解謎帶進公共電視文化。",legacy:"獲得艾美獎最佳戲劇並改變觀眾參與方式；即使結局有爭議，後來的高概念謎團劇幾乎都必須回應它的影響。",...receptionSources("Lost ABC","tt0411008")},
  "The Office":{audience:"觀眾對角色陪伴感與可反覆觀看性極高，Michael 離開後的品質起伏則是最常見的保留。",critics:"影評肯定它把英版的尷尬喜劇改造成更溫暖的美式職場群像，並讓偽紀錄形式成為主流喜劇語言。",legacy:"艾美獎最佳喜劇等肯定之外，串流世代的長期重看與迷因文化，讓它在完結後仍不斷吸收新觀眾。",...receptionSources("The Office US NBC","tt0386676")},
  "Arrested Development":{audience:"觀眾喜愛極密集的伏筆、回收與旁白笑點，也常認為它需要重看才能真正接住；復活季度的評價較為分歧。",critics:"評論界讚賞它把家庭鬧劇寫成高度連鎖的敘事機器，形式與笑點密度都遠超當時情境喜劇慣例。",legacy:"播出時收視有限卻獲艾美獎最佳喜劇，後來透過 DVD 與串流形成經典地位，成為「太早出現」的代表作品。",...receptionSources("Arrested Development","tt0367279")},
  "Battlestar Galactica":{audience:"觀眾投入生存危機、政治與宗教辯論，前期幾季尤受推崇；後期神話線與結局的超自然取向較具爭議。",critics:"影評肯定它借太空歌劇討論戰爭、恐怖主義、民主與人性，讓類型劇直接回應九一一後的政治焦慮。",legacy:"Peabody 與多項技術獎肯定其野心；即使未獲最佳戲劇艾美，它仍是現代嚴肅科幻電視不可繞過的基準。",...receptionSources("Battlestar Galactica 2004","tt0407362")},
};

export default function Home() {
  const [genre,setGenre]=useState("全部"); const [sort,setSort]=useState("契合度"); const [weights,setWeights]=useState(criteria.map(()=>10));
  const [saved,setSaved]=useState<string[]>(["六呎風雲"]); const [compare,setCompare]=useState<Show[]>([]); const [active,setActive]=useState<Show|null>(null); const [weightsOpen,setWeightsOpen]=useState(false); const [view,setView]=useState("探索"); const [quiz,setQuiz]=useState(0); const [answers,setAnswers]=useState<string[]>([]); const [quizOpen,setQuizOpen]=useState(false); const [quizPhase,setQuizPhase]=useState<"taste"|"mood">("taste"); const [mood,setMood]=useState(""); const [groupPrefs,setGroupPrefs]=useState([3,4,2,1]); const [advancedOpen,setAdvancedOpen]=useState(false); const [posters,setPosters]=useState<Record<string,string>>({}); const [showAll,setShowAll]=useState(false); const [notes,setNotes]=useState<Record<string,string>>({}); const [toast,setToast]=useState("");
  const personalScore=(s:Show)=>{const factors=[Math.min(100,s.score+(s.genre==="劇情"||s.genre==="犯罪"?3:-2)),Math.min(100,s.score+(s.year<2010?4:0)+(s.genre==="科幻"||s.genre==="迷你影集"?3:0)),Math.min(100,s.score+(s.platform==="HBO"||s.platform==="FX"?3:-1)),s.score];const sum=groupPrefs.reduce((a,b)=>a+b,0);return Math.round(factors.reduce((n,v,i)=>n+v*groupPrefs[i],0)/sum)};
  const list=shows.filter(s=>genre==="全部"||s.genre===genre).sort((a,b)=>sort==="年份"?b.year-a.year:sort==="平台"?a.platform.localeCompare(b.platform):sort==="作品評分"?b.score-a.score:personalScore(b)-personalScore(a));
  useEffect(()=>{let alive=true;Promise.all(shows.map(async s=>{try{const response=await fetch(`https://api.tvmaze.com/singlesearch/shows?q=${encodeURIComponent(imageQueryByTitle[s.title])}`);if(!response.ok)return [s.title,""] as const;const data=await response.json();return [s.title,data.image?.original||data.image?.medium||""] as const}catch{return [s.title,""] as const}})).then(items=>{if(alive)setPosters(Object.fromEntries(items))});return()=>{alive=false}},[]);
  useEffect(()=>{let timer=0;try{const stored=window.localStorage.getItem("series-notes");if(stored)timer=window.setTimeout(()=>setNotes(JSON.parse(stored)),0)}catch{}return()=>window.clearTimeout(timer)},[]);
  const quizData=[
    {q:"一個故事結束後，你最希望留下什麼？",a:["對世界的新理解","某個忘不掉的人","一種純粹的震撼"]},
    {q:"你能接受一部好作品走得多慢？",a:["愈慢愈好，讓我住進去","只要每一步都有意義","我需要被故事往前推"]},
    {q:"如果結局並不討喜，但非常誠實？",a:["這正是我想看的","可以，但前提是完整","我希望至少得到情感回報"]},
    {q:"你更願意重看哪一種時刻？",a:["突然理解整個制度","人物做出艱難選擇","精準又漂亮的高潮"]},
  ];
  const answerQuiz=(answer:string)=>{const next=[...answers,answer];setAnswers(next);if(quiz<quizData.length-1)setQuiz(quiz+1);else{const cerebral=next.filter(x=>x.includes("理解")||x.includes("制度")||x.includes("誠實")).length;setWeights(cerebral>=2?[16,13,10,14,6,5,10,12,7,7]:[9,17,13,8,8,12,12,7,7,7]);setGroupPrefs(cerebral>=2?[3,4,3,2]:[4,3,2,1]);setQuizPhase("mood")}};
  const chooseMood=(choice:string)=>{setMood(choice);setQuizOpen(false)};
  const restartExplore=()=>{setQuiz(0);setAnswers([]);setMood("");setQuizPhase("taste");setQuizOpen(true)};
  const prefWords=["不太重要","普通","很重要","最重要"];
  const groupData=[{name:"故事與人物",note:"人物、劇本、結局與觀看推進感"},{name:"思想與餘韻",note:"跨世代命題、重看價值與時間驗證"},{name:"創作與突破",note:"形式創新、影響力與製作品質"},{name:"歷史與共識",note:"評論、獎項與長期文化位置"}];
  const toggleCompare=(s:Show)=>setCompare(c=>c.some(x=>x.title===s.title)?c.filter(x=>x.title!==s.title):c.length<3?[...c,s]:c);
  const toggleSaved=(s:Show)=>{const isSaved=saved.includes(s.title);setSaved(list=>isSaved?list.filter(title=>title!==s.title):[...list,s.title]);setToast(isSaved?`已從片單移除 ${imageQueryByTitle[s.title]}`:`已加入片單：${imageQueryByTitle[s.title]}`);window.setTimeout(()=>setToast(""),1800)};
  const updateNote=(title:string,value:string)=>{const next={...notes,[title]:value};setNotes(next);try{window.localStorage.setItem("series-notes",JSON.stringify(next))}catch{}}
  return <main className="app-shell" data-quiz-complete={answers.length>0&&Boolean(mood)}>
    <aside className="sidebar"><a className="brand" href="#">時間留下的影集<span>THE SERIES THAT REMAIN</span></a><div className="side-nav">{["探索","排行榜","我的片單","評分方法"].map(x=><button key={x} className={view===x?"active":""} onClick={()=>setView(x)}><i>{x==="探索"?"◌":x==="排行榜"?"≡":x==="我的片單"?"◇":"?"}</i>{x}</button>)}</div><div className="side-note"><span>你的觀看傾向</span><b>{answers.length?"思想考掘型":"尚未建立"}</b>{mood&&<small className="mood-context">今晚：{mood}</small>}<div className="side-note-actions">{mood&&<button onClick={()=>{setQuizPhase("mood");setQuizOpen(true)}}>調整今晚心情</button>}<button onClick={()=>{setQuiz(0);setAnswers([]);setMood("");setQuizPhase("taste");setQuizOpen(true)}}>{answers.length?"重新探索":"開始探索"}</button></div></div></aside>
    <div className="workspace"><header className="dash-top"><div><small>1990—PRESENT · 100 部已完結作品</small><h1>{view}</h1></div><div className="search">搜尋 100 部作品　⌕</div></header>
    {view==="探索"&&<><section className="welcome"><div><span>{answers.length?"你的觀看人格":"從你的觀看方式開始"}</span><h2>{answers.length?<>思想考掘型，<br/>但今晚可以不一樣。</>:<>故事結束之後，<br/>什麼仍留在你身上？</>}</h2><p>{answers.length?`你長期偏愛有思想餘韻的作品${mood?`；今晚想要「${mood}」`:"。再告訴我們今晚的心情，推薦會更貼近此刻"}。`:"我們只談已經說完的故事。先認識你的觀看方式，再從時間留下的作品裡，找出真正適合你的那一部。"}</p><div className="explore-actions"><button className="primary" onClick={()=>{if(answers.length)setQuizPhase("mood");setQuizOpen(true)}}>{answers.length?"換一種今晚心情":"開始探索"}　→</button>{answers.length>0&&<button className="restart-explore" onClick={restartExplore}>重新探索　↻</button>}</div></div><div className="feature-score"><small>今晚最適合你</small><h3>{answers.length?(mood==="想笑一笑"?"Fleabag":"Six Feet Under"):"The Wire"}</h3><p>{answers.length?(mood==="想笑一笑"?"倫敦生活":"六呎風雲"):"火線重案組 · 2002—2008"}</p><div className="hero-score-pair"><span><b>{answers.length?"92":"98"}%</b>契合度</span><span><b>{answers.length?(mood==="想笑一笑"?featured[10].score:featured[1].score):featured[0].score}</b>作品評分</span></div></div></section><section className="stats"><div><span>收錄作品</span><b>{shows.length}</b><small>都是已經完結的劇集</small></div><button className="stat-link" onClick={()=>setView("我的片單")}><span>你的片單</span><b>{saved.length}</b><small>看看你為下一個夜晚留下的片單　→</small></button><div><span>今晚情境</span><b className="mood-stat">{mood||"尚未選擇"}</b><small>{mood?"心情變了，也可以重新選擇":"完成探索後，推薦會更貼近此刻"}</small></div></section><section className="rec"><div className="panel-title"><div><small>為你而選 · {mood||"依長期品味"}</small><h2>時間沖刷不去的三部作品</h2></div><button onClick={()=>setView("排行榜")}>看看更多可能 →</button></div><div className="compact-grid three">{(mood==="想笑一笑"?[featured[10],featured[6],featured[1]]:mood==="想被安慰"?[featured[1],featured[10],featured[7]]:featured.slice(0,3)).map((s,i)=><article key={s.title} onClick={()=>setActive(s)}><div className="mini-cover" style={posters[s.title]?{backgroundImage:`linear-gradient(180deg,transparent,rgba(31,48,42,.7)),url(${posters[s.title]})`}:undefined}><span>0{i+1}</span><div className="cover-scores"><b>{personalScore(s)}%</b><small>契合度</small></div></div><div className="card-meta"><small>{s.genre} · {s.platform}</small><span>作品評分 {s.score}</span></div><h3>{imageQueryByTitle[s.title]}</h3><em>{s.title}</em><p>{s.note}</p><div className="match-reason">{i===0?"最符合你現在想看的心情":i===1?"同樣重視人物，情緒更內斂":"同樣有深度，節奏更緊湊"}</div></article>)}</div></section></>}
    {view==="排行榜"&&<section className="ranking"><div className="section-title"><div><span>FOR YOU · 100</span><h2>為你排序</h2><p>依「{answers.length?"思想考掘型":"尚未建立的品味"}」{mood&&<>與今晚「{mood}」</>}排列。契合度回答現在適不適合你；作品評分則回答它是否經得起時間。</p><div className="ranking-context"><span>觀看傾向：{answers.length?"思想考掘型":"尚未建立"}</span><span>今晚：{mood||"尚未選擇"}</span></div></div><button className="outline" onClick={()=>setWeightsOpen(!weightsOpen)}>微調我的品味</button></div>
      {weightsOpen&&<div className="preference-panel"><div className="preference-head"><div><h3>看影集時，你最在意什麼？</h3><p>憑直覺選就好。沒有標準答案，也可以隨時回來改變心意。</p></div><button onClick={()=>setAdvancedOpen(!advancedOpen)}>{advancedOpen?"簡單一點":"看看我們怎麼選"}</button></div><div className="preference-groups">{groupData.map((g,i)=><article key={g.name}><small>0{i+1}</small><h4>{g.name}</h4><p>{g.note}</p><div>{prefWords.map((word,n)=><button key={word} className={groupPrefs[i]===n+1?"active":""} onClick={()=>setGroupPrefs(v=>v.map((x,j)=>j===i?n+1:x))}>{word}</button>)}</div></article>)}</div>{advancedOpen&&<div className="advanced"><span>這份名單還參考了十個面向</span><p>{criteria.map((c,i)=><i key={c}>{c}<b>{weights[i]}%</b></i>)}</p><small>數字只是幫助我們保持一致；真正重要的，仍然是每部作品留下了什麼。</small></div>}</div>}
      <div className="tools"><div id="genres">{["全部","劇情","犯罪","喜劇","科幻","迷你影集"].map(g=><button className={genre===g?"active":""} onClick={()=>setGenre(g)} key={g}>{g}</button>)}</div><label>排序：<select value={sort} onChange={e=>setSort(e.target.value)}><option>契合度</option><option>作品評分</option><option>年份</option><option>平台</option></select></label></div>
      <div className="cards">{list.slice(0,showAll?list.length:12).map((s,i)=><article key={s.title} onClick={()=>setActive(s)}><div className="poster" style={posters[s.title]?{backgroundImage:`linear-gradient(180deg,transparent 35%,rgba(20,32,28,.88)),url(${posters[s.title]})`}:undefined}><span>{String(i+1).padStart(2,"0")}</span><div className="poster-score"><b>{personalScore(s)}%</b><small>契合度</small></div></div><div className="card-copy"><div className="card-meta"><small>{s.genre} · {s.platform} · {s.year}—{s.end}</small><span>作品評分 {s.score}</span></div><h3>{imageQueryByTitle[s.title]}</h3><em>{s.title}</em><p>{s.note}</p><div className="card-actions"><button className={saved.includes(s.title)?"saved-action":""} onClick={e=>{e.stopPropagation();toggleSaved(s)}}>{saved.includes(s.title)?"✓ 已在片單":"＋ 加入片單"}</button><button onClick={e=>{e.stopPropagation();toggleCompare(s)}}>{compare.some(x=>x.title===s.title)?"✓ 比較中":"⇄ 比較"}</button></div></div></article>)}</div><button className="more" onClick={()=>setShowAll(!showAll)}>{showAll?"收起作品":"瀏覽全部 " + list.length + " 部作品"}</button>
    </section>}
    {view==="我的片單"&&<section className="ranking"><div className="section-title"><div><span>MY LIST</span><h2>留給下一個晚上的故事</h2><p>收藏那些讓你有點心動、但還沒準備好立刻開始的作品。</p><div className="ranking-context"><span>觀看傾向：{answers.length?"思想考掘型":"尚未建立"}</span><span>今晚：{mood||"尚未選擇"}</span></div></div></div><div className="cards">{shows.filter(s=>saved.includes(s.title)).map(s=><article key={s.title} onClick={()=>setActive(s)}><div className="poster" style={posters[s.title]?{backgroundImage:`linear-gradient(180deg,transparent 35%,rgba(20,32,28,.88)),url(${posters[s.title]})`}:undefined}><div className="poster-score"><b>{personalScore(s)}%</b><small>契合度</small></div></div><div className="card-copy"><div className="card-meta"><small>{s.genre} · {s.platform}</small><span>作品評分 {s.score}</span></div><h3>{imageQueryByTitle[s.title]}</h3><em>{s.title}</em><p>{notes[s.title]?`「${notes[s.title]}」`:s.note}</p></div></article>)}</div></section>}
    {view==="評分方法"&&<section className="method method-deep"><div className="method-intro"><span>HOW WE READ</span><h2>我們不評哪部最好，<br/>而是哪部仍值得被重看。</h2><p>熱度會消退，技術會過時，觀眾也會改變。真正留下來的作品，往往不是毫無缺點，而是在多年之後，仍能讓人重新理解角色、時代，甚至自己。</p></div><div className="method-principles"><article><b>01</b><h3>結局也是作品的一部分</h3><p>我們只收錄已完結影集。因為一個故事如何承擔它曾經許下的承諾，必須等到最後一幕才能判斷。</p></article><article><b>02</b><h3>影響力不等於今天仍好看</h3><p>開創先例值得被記住，但歷史地位不能代替觀看經驗。我們同時追問：它曾經改變什麼？現在還能帶來什麼？</p></article><article><b>03</b><h3>缺點不會被平均掉</h3><p>有些缺陷會動搖整部作品，有些反而來自它的野心。分數不是把優缺點相加，而是判斷它們如何共同構成作品。</p></article></div><div className="evidence"><div><span>我們能確認的事</span><h3>事實層</h3><p>播出年份、完結狀態、評論趨勢、獎項、創作者影響，以及作品在後來影集中的可見痕跡。</p></div><div><span>我們必須承認的事</span><h3>判斷層</h3><p>人物是否成立、命題是否深刻、結局是否誠實、重看是否長出新意。這些無法假裝客觀，因此每一項都必須留下理由。</p></div></div><div className="criteria-block"><div><span>THE TEN LENSES</span><h3>十個觀看角度，不是十條真理。</h3><p>它們讓不同作品能被放在同一張桌上討論，也提醒我們：製作精良、令人上癮與真正重要，從來不是同一件事。</p></div><ol>{criteria.map((c,i)=><li key={c}><b>{String(i+1).padStart(2,"0")}</b><span>{c}</span></li>)}</ol></div><figure className="spirit-quote"><blockquote>“The great movies enlarge us, they civilize us, they make us more decent people.”</blockquote><p>偉大的作品拓展我們的生命經驗，也讓我們成為更理解他人的人。</p><figcaption>— Roger Ebert，<a href="https://www.rogerebert.com/roger-ebert/eberts-walk-of-fame-remarks" target="_blank" rel="noreferrer">Hollywood Walk of Fame Remarks</a>，2005</figcaption></figure></section>}
    </div>

    {compare.length>0&&<div className="comparebar"><span>比較作品（{compare.length}/3）</span>{compare.map(s=><button key={s.title} onClick={()=>toggleCompare(s)}>{imageQueryByTitle[s.title]} <small>{s.title}</small> ×</button>)}<button className="go" onClick={()=>setActive(compare[0])}>放在一起看看 →</button></div>}
    {active&&<div className="modal" onClick={()=>setActive(null)}><article className="detail" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setActive(null)}>×</button>{posters[active.title]&&<div className="full-poster" style={{backgroundImage:`url(${posters[active.title]})`}}/>}<div className="detail-copy"><small>{active.genre} · {active.platform} · {active.seasons}</small><h2>{imageQueryByTitle[active.title]}</h2><em>{active.title} · {active.year}—{active.end}</em><div className="detail-scores"><div><b>{personalScore(active)}%</b><span>與你的契合度</span><small>依觀看品味與今晚心情</small></div><div><b>{active.score}</b><span>作品評分</span><small>依十個觀看角度綜合判斷</small></div></div><h3>它為什麼值得留下？</h3><p>{active.note}</p><div className="score-summary"><b>本作最突出的三個面向</b><small>完整作品評分由十個觀看角度綜合而成；以下摘錄得分最高的三項。</small></div><div className="scorelines">{criteria.slice(0,3).map((c,i)=><label key={c}>{c}<span><i style={{width:`${active.score-i*2}%`}}/></span><b>{active.score-i*2}</b></label>)}</div>{externalReception[imageQueryByTitle[active.title]]&&<section className="outside-voice"><div className="outside-head"><small>RECEPTION &amp; LEGACY</small><h3>外界如何記得它</h3><p>不同資料代表不同觀點，不合併成另一個分數。</p></div><article><b>觀眾反應</b><p>{externalReception[imageQueryByTitle[active.title]].audience}</p><div><a href={externalReception[imageQueryByTitle[active.title]].imdb} target="_blank" rel="noreferrer">IMDb 觀眾評論 ↗</a><a href={externalReception[imageQueryByTitle[active.title]].reddit} target="_blank" rel="noreferrer">Reddit 討論 ↗</a></div></article><article><b>影評共識</b><p>{externalReception[imageQueryByTitle[active.title]].critics}</p></article><article><b>獎項與時間</b><p>{externalReception[imageQueryByTitle[active.title]].legacy}</p><a href={externalReception[imageQueryByTitle[active.title]].awards} target="_blank" rel="noreferrer">Television Academy 資料 ↗</a></article><small className="source-note">摘要綜合公開評分、觀眾討論、專業評論與獎項紀錄；它描述常見反應，不代表所有人的意見。</small></section>}<button className={`primary save-primary ${saved.includes(active.title)?"is-saved":""}`} onClick={()=>toggleSaved(active)}>{saved.includes(active.title)?"✓ 已在我的片單 · 點擊移除":"＋ 留到我的片單"}</button><div className="personal-note"><div><h3>留一句話給自己</h3><small>看前的期待、看完的感受，或任何不想忘記的念頭。</small></div><textarea aria-label={`寫下關於 ${imageQueryByTitle[active.title]} 的心得`} maxLength={280} placeholder="例如：第二季之後，我開始用不同的眼光看待這個角色……" value={notes[active.title]||""} onChange={e=>updateNote(active.title,e.target.value)}/><span>{(notes[active.title]||"").length} / 280 · 自動保存在這台裝置</span></div></div></article></div>}
    {quizOpen&&<div className="quiz"><article><button className="close" onClick={()=>setQuizOpen(false)}>×</button>{quizPhase==="taste"?<><div className="quiz-progress"><span style={{width:`${((quiz+1)/quizData.length)*100}%`}}/></div><small>長期觀看品味 · {quiz+1} / {quizData.length}</small><h2>{quizData[quiz].q}</h2><p>沒有正確答案。請選擇第一個接近你直覺的回答。</p><div className="answers">{quizData[quiz].a.map((a,i)=><button key={a} onClick={()=>answerQuiz(a)}><b>{String.fromCharCode(65+i)}</b><span>{a}</span><i>→</i></button>)}</div></>:<><div className="quiz-progress complete"><span/></div><small>最後一題 · 此刻的你</small><h2>今晚，你想從一部影集得到什麼？</h2><p>這不會改變你的長期品味，只影響這一次的推薦。</p><div className="mood-grid">{["想笑一笑","想被安慰","想緊張刺激","想沉浸思考","給我一個意外"].map((m,i)=><button key={m} onClick={()=>chooseMood(m)}><b>0{i+1}</b><span>{m}</span><i>→</i></button>)}</div></>}<button className="skip" onClick={()=>setQuizOpen(false)}>稍後再回答</button></article></div>}{toast&&<div className="toast" role="status">{toast}</div>}
  </main>
}
