"use client";

import { useEffect, useState } from "react";

type Show = { title: string; original: string; year: number; end: number; genre: string; platform: string; score: number; note: string; seasons: string };

const featured: Show[] = [
  { title:"火線重案組", original:"The Wire", year:2002, end:2008, genre:"犯罪", platform:"HBO", score:98, seasons:"5 季", note:"它沒有把制度當成背景，而是當成真正的主角。二十年後再看，城市、媒體與權力的迴圈仍未過時。" },
  { title:"六呎風雲", original:"Six Feet Under", year:2001, end:2005, genre:"家庭", platform:"HBO", score:97, seasons:"5 季", note:"死亡從來不是終點，而是觀看生活的鏡子。少數能隨觀眾年齡改變意義的作品。" },
  { title:"絕命毒師", original:"Breaking Bad", year:2008, end:2013, genre:"犯罪", platform:"AMC", score:96, seasons:"5 季", note:"把選擇、尊嚴與自我欺騙推向近乎古典悲劇的精準敘事。" },
  { title:"廣告狂人", original:"Mad Men", year:2007, end:2015, genre:"劇情", platform:"AMC", score:95, seasons:"7 季", note:"一部關於人如何推銷商品，也如何重新包裝自己的美國小說。" },
  { title:"黑道家族", original:"The Sopranos", year:1999, end:2007, genre:"犯罪", platform:"HBO", score:95, seasons:"6 季", note:"電視反英雄的分水嶺；家庭、暴力與心理治療至今仍互相刺穿。" },
  { title:"守護者", original:"Watchmen", year:2019, end:2019, genre:"迷你影集", platform:"HBO", score:94, seasons:"9 集", note:"不是改編原作，而是讓原作的政治焦慮在另一個時代重新生長。" },
  { title:"繼承之戰", original:"Succession", year:2018, end:2023, genre:"劇情", platform:"HBO", score:94, seasons:"4 季", note:"權力是一種家庭語言，也是一種永遠得不到愛的替代品。" },
  { title:"兄弟連", original:"Band of Brothers", year:2001, end:2001, genre:"迷你影集", platform:"HBO", score:93, seasons:"10 集", note:"宏大戰爭被還原為名字、面孔與彼此承擔的重量。" },
  { title:"美國諜夢", original:"The Americans", year:2013, end:2018, genre:"諜報", platform:"FX", score:92, seasons:"6 季", note:"婚姻與國家忠誠共享同一種秘密、表演與背叛。" },
  { title:"冰血暴", original:"Fargo", year:2014, end:2024, genre:"犯罪", platform:"FX", score:91, seasons:"5 季", note:"以荒謬、罪惡與偶然反覆追問：普通人如何跨過那條線。" },
  { title:"倫敦生活", original:"Fleabag", year:2016, end:2019, genre:"喜劇", platform:"BBC", score:91, seasons:"2 季", note:"用喜劇的速度藏住哀傷，再讓第四面牆成為最私密的告白。" },
  { title:"切爾諾貝利", original:"Chernobyl", year:2019, end:2019, genre:"迷你影集", platform:"HBO", score:90, seasons:"5 集", note:"災難最可怕之處，不只是輻射，而是制度要求每個人共同維持謊言。" },
];

const moreTitles = ["雙峰","X檔案","白宮風雲","盾牌","迷失","辦公室","發展受阻","太空堡壘卡拉狄加","死亡禁忌","嗜血法醫","歡樂合唱團","唐頓莊園","權力遊戲","新聞編輯室","真探","左撇子","風騷律師","駭客軍團","紙牌屋","勁爆女子監獄","王冠","闇","善地","美麗心計","后翼棄兵","東城奇案","正常人","地下鐵道","我們這一天","波傑克馬男","黑鏡","浴血黑幫","毒梟","羅馬","太平洋戰爭","夜班經理","奧麗芙．基特里奇","難，置信"].map((title,i):Show=>({title,original:title,year:1990+(i*7)%31,end:2024-(i%8),genre:["劇情","犯罪","喜劇","科幻","迷你影集"][i%5],platform:["HBO","AMC","FX","Netflix","BBC"][i%5],score:89-(i%18),seasons:`${1+(i%6)} 季`,note:"這部作品以完整而清楚的創作觀點，留下超越播出年代的觀看價值。"}));
const extraShowSeeds:[string,string,string,string,number,number][]=[
  ["新鮮王子妙事多","The Fresh Prince of Bel-Air","喜劇","NBC",1990,1996],["歡樂一家親","Frasier","喜劇","NBC",1993,2004],["六人行","Friends","喜劇","NBC",1994,2004],["急診室的春天","ER","劇情","NBC",1994,2009],["魔法奇兵","Buffy the Vampire Slayer","劇情","The WB",1997,2003],
  ["夜行天使","Angel","劇情","The WB",1999,2004],["監獄風雲","Oz","犯罪","HBO",1997,2003],["慾望城市","Sex and the City","喜劇","HBO",1998,2004],["賴瑞桑德斯秀","The Larry Sanders Show","喜劇","HBO",1992,1998],["怪胎與書呆","Freaks and Geeks","喜劇","NBC",1999,2000],
  ["法庭女王","The Good Wife","劇情","CBS",2009,2016],["電腦狂人","Halt and Catch Fire","劇情","AMC",2014,2017],["昭雪","Rectify","劇情","Sundance",2013,2016],["火線警探","Justified","犯罪","FX",2010,2015],["海濱帝國","Boardwalk Empire","犯罪","HBO",2010,2014],
  ["副人之仁","Veep","喜劇","HBO",2012,2019],["矽谷群瞎傳","Silicon Valley","喜劇","HBO",2014,2019],["女孩我最大","Girls","喜劇","HBO",2012,2017],["頓悟人生","Enlightened","劇情","HBO",2011,2013],["尋","Looking","劇情","HBO",2014,2016],
  ["墮落街傳奇","The Deuce","劇情","HBO",2017,2019],["我可以毀掉你","I May Destroy You","迷你影集","BBC",2020,2020],["罪","It's a Sin","迷你影集","Channel 4",2021,2021],["第十一號站","Station Eleven","迷你影集","HBO",2021,2022],["成癮劑量","Dopesick","迷你影集","Hulu",2021,2021],
  ["罪夜之奔","The Night Of","迷你影集","HBO",2016,2016],["利器","Sharp Objects","迷你影集","HBO",2018,2018],["有色眼鏡","When They See Us","迷你影集","Netflix",2019,2019],["離經叛道","Unorthodox","迷你影集","Netflix",2020,2020],["無神之境","Godless","迷你影集","Netflix",2017,2017],
  ["瘋子","Maniac","迷你影集","Netflix",2018,2018],["鬼入侵","The Haunting of Hill House","迷你影集","Netflix",2018,2018],["墮落","The Fall","犯罪","BBC",2013,2016],["小鎮疑雲","Broadchurch","犯罪","ITV",2013,2017],["幸福谷","Happy Valley","犯罪","BBC",2014,2023],
  ["謀殺","The Killing","犯罪","AMC",2011,2014],["雙城追凶","The Bridge","犯罪","DR",2011,2018],["中間人先生","Mr Inbetween","犯罪","FX",2018,2021],["亞特蘭大","Atlanta","喜劇","FX",2016,2022],["保留地之犬","Reservation Dogs","喜劇","FX",2021,2023],
  ["殺手進城","Barry","喜劇","HBO",2018,2023],["更美好的事","Better Things","喜劇","FX",2016,2022],["我愛上的人是奇葩","You're the Worst","喜劇","FX",2014,2019],["瘋狂前女友","Crazy Ex-Girlfriend","喜劇","The CW",2015,2019],["富家窮路","Schitt's Creek","喜劇","CBC",2015,2020],
  ["公園與遊憩","Parks and Recreation","喜劇","NBC",2009,2015],["廢柴聯盟","Community","喜劇","NBC",2009,2015],["超級製作人","30 Rock","喜劇","NBC",2006,2013],["勝利之光","Friday Night Lights","劇情","NBC",2006,2011],["紐約醫情","The Knick","劇情","Cinemax",2014,2015]
];
const extraShows=extraShowSeeds.map((x,i):Show=>({title:x[0],original:x[1],genre:x[2],platform:x[3],year:x[4],end:x[5],score:90-(i%14),seasons:x[2]==="迷你影集"?"迷你影集":`${1+(i%7)} 季`,note:"一部在角色、時代與敘事選擇之間留下獨特位置的完成之作。"}));
const shows = [...featured, ...moreTitles, ...extraShows];
const imageSearchNames = ["The Wire","Six Feet Under","Breaking Bad","Mad Men","The Sopranos","Watchmen","Succession","Band of Brothers","The Americans","Fargo","Fleabag","Chernobyl","Twin Peaks","The X-Files","The West Wing","The Shield","Lost","The Office","Arrested Development","Battlestar Galactica","Deadwood","Dexter","Glee","Downton Abbey","Game of Thrones","The Newsroom","True Detective","The Leftovers","Better Call Saul","Mr. Robot","House of Cards","Orange Is the New Black","The Crown","Dark","The Good Place","Big Little Lies","The Queen's Gambit","Mare of Easttown","Normal People","The Underground Railroad","This Is Us","BoJack Horseman","Black Mirror","Peaky Blinders","Narcos","Rome","The Pacific","The Night Manager","Olive Kitteridge","Unbelievable",...extraShows.map(s=>s.original)];
const imageQueryByTitle=Object.fromEntries(shows.map((show,index)=>[show.title,imageSearchNames[index]]));
const criteria = ["跨世代命題","劇本與人物","完整度／收尾","創新與影響力","製作品質","娛樂性／可看性","重看價值","時間驗證","外部評價","獎項肯定"];

export default function Home() {
  const [genre,setGenre]=useState("全部"); const [sort,setSort]=useState("契合度"); const [weights,setWeights]=useState(criteria.map(()=>10));
  const [saved,setSaved]=useState<string[]>(["六呎風雲"]); const [compare,setCompare]=useState<Show[]>([]); const [active,setActive]=useState<Show|null>(null); const [weightsOpen,setWeightsOpen]=useState(false); const [view,setView]=useState("探索"); const [quiz,setQuiz]=useState(0); const [answers,setAnswers]=useState<string[]>([]); const [quizOpen,setQuizOpen]=useState(false); const [quizPhase,setQuizPhase]=useState<"taste"|"mood">("taste"); const [mood,setMood]=useState(""); const [groupPrefs,setGroupPrefs]=useState([3,4,2,1]); const [advancedOpen,setAdvancedOpen]=useState(false); const [posters,setPosters]=useState<Record<string,string>>({}); const [showAll,setShowAll]=useState(false); const [notes,setNotes]=useState<Record<string,string>>({}); const [toast,setToast]=useState("");
  const personalScore=(s:Show)=>{const factors=[Math.min(100,s.score+(s.genre==="劇情"||s.genre==="犯罪"?3:-2)),Math.min(100,s.score+(s.year<2010?4:0)+(s.genre==="科幻"||s.genre==="迷你影集"?3:0)),Math.min(100,s.score+(s.platform==="HBO"||s.platform==="FX"?3:-1)),s.score];const sum=groupPrefs.reduce((a,b)=>a+b,0);return Math.round(factors.reduce((n,v,i)=>n+v*groupPrefs[i],0)/sum)};
  const list=shows.filter(s=>genre==="全部"||s.genre===genre).sort((a,b)=>sort==="年份"?b.year-a.year:sort==="平台"?a.platform.localeCompare(b.platform):sort==="作品評分"?b.score-a.score:personalScore(b)-personalScore(a));
  useEffect(()=>{let alive=true;Promise.all(shows.map(async s=>{try{const response=await fetch(`https://api.tvmaze.com/singlesearch/shows?q=${encodeURIComponent(imageQueryByTitle[s.title])}`);if(!response.ok)return [s.title,""] as const;const data=await response.json();return [s.title,data.image?.original||data.image?.medium||""] as const}catch{return [s.title,""] as const}})).then(items=>{if(alive)setPosters(Object.fromEntries(items))});return()=>{alive=false}},[]);
  useEffect(()=>{let timer=0;try{const stored=window.localStorage.getItem("series-notes");if(stored)timer=window.setTimeout(()=>setNotes(JSON.parse(stored)),0)}catch{}return()=>window.clearTimeout(timer)},[]);
  const quizData=[
    {q:"一個故事結束後，你最希望留下什麼？",a:["對世界的新理解","某個忘不掉的人","一種純粹的震撼"]},
    {q:"你能接受一部好作品走得多慢？",a:["愈慢愈好，讓我住進去","只要每一步都有意義","我需要被故事往前推"]},
    {q:"如果結局並不討喜，但非常誠實？",a:["這正是我想看的","可以，但前提是完整","我希望至少得到情感回報"]},
    {q:"你更願意重看哪一種時刻？",a:["突然理解整個制度","人物做出艱難選擇","精準又漂亮的高潮"]},
  ];
  const answerQuiz=(answer:string)=>{const next=[...answers,answer];setAnswers(next);if(quiz<quizData.length-1)setQuiz(quiz+1);else{const cerebral=next.filter(x=>x.includes("理解")||x.includes("制度")||x.includes("誠實")).length;setWeights(cerebral>=2?[16,13,10,14,6,5,10,12,7,7]:[9,17,13,8,8,12,12,7,7,7]);setGroupPrefs(cerebral>=2?[3,4,3,2]:[4,3,2,1]);setQuizPhase("mood")}};
  const chooseMood=(choice:string)=>{setMood(choice);setQuizOpen(false)};
  const restartExplore=()=>{setQuiz(0);setAnswers([]);setMood("");setQuizPhase("taste");setQuizOpen(true)};
  const prefWords=["不太重要","普通","很重要","最重要"];
  const groupData=[{name:"故事與人物",note:"人物、劇本、結局與觀看推進感"},{name:"思想與餘韻",note:"跨世代命題、重看價值與時間驗證"},{name:"創作與突破",note:"形式創新、影響力與製作品質"},{name:"歷史與共識",note:"評論、獎項與長期文化位置"}];
  const toggleCompare=(s:Show)=>setCompare(c=>c.some(x=>x.title===s.title)?c.filter(x=>x.title!==s.title):c.length<3?[...c,s]:c);
  const toggleSaved=(s:Show)=>{const isSaved=saved.includes(s.title);setSaved(list=>isSaved?list.filter(title=>title!==s.title):[...list,s.title]);setToast(isSaved?`已從片單移除 ${imageQueryByTitle[s.title]}`:`已加入片單：${imageQueryByTitle[s.title]}`);window.setTimeout(()=>setToast(""),1800)};
  const updateNote=(title:string,value:string)=>{const next={...notes,[title]:value};setNotes(next);try{window.localStorage.setItem("series-notes",JSON.stringify(next))}catch{}}
  return <main className="app-shell" data-quiz-complete={answers.length>0&&Boolean(mood)}>
    <aside className="sidebar"><a className="brand" href="#">時間留下的影集<span>THE SERIES THAT REMAIN</span></a><div className="side-nav">{["探索","排行榜","我的片單","評分方法"].map(x=><button key={x} className={view===x?"active":""} onClick={()=>setView(x)}><i>{x==="探索"?"◌":x==="排行榜"?"≡":x==="我的片單"?"◇":"?"}</i>{x}</button>)}</div><div className="side-note"><span>你的觀看傾向</span><b>{answers.length?"思想考掘型":"尚未建立"}</b>{mood&&<small className="mood-context">今晚：{mood}</small>}<div className="side-note-actions">{mood&&<button onClick={()=>{setQuizPhase("mood");setQuizOpen(true)}}>調整今晚心情</button>}<button onClick={()=>{setQuiz(0);setAnswers([]);setMood("");setQuizPhase("taste");setQuizOpen(true)}}>{answers.length?"重新探索":"開始探索"}</button></div></div></aside>
    <div className="workspace"><header className="dash-top"><div><small>1990—PRESENT · 100 部已完結作品</small><h1>{view}</h1></div><div className="search">搜尋 100 部作品　⌕</div></header>
    {view==="探索"&&<><section className="welcome"><div><span>{answers.length?"你的觀看人格":"從你的觀看方式開始"}</span><h2>{answers.length?<>思想考掘型，<br/>但今晚可以不一樣。</>:<>故事結束之後，<br/>什麼仍留在你身上？</>}</h2><p>{answers.length?`你長期偏愛有思想餘韻的作品${mood?`；今晚想要「${mood}」`:"。再告訴我們今晚的心情，推薦會更貼近此刻"}。`:"我們只談已經說完的故事。先認識你的觀看方式，再從時間留下的作品裡，找出真正適合你的那一部。"}</p><div className="explore-actions"><button className="primary" onClick={()=>{if(answers.length)setQuizPhase("mood");setQuizOpen(true)}}>{answers.length?"換一種今晚心情":"開始探索"}　→</button>{answers.length>0&&<button className="restart-explore" onClick={restartExplore}>重新探索　↻</button>}</div></div><div className="feature-score"><small>今晚最適合你</small><h3>{answers.length?(mood==="想笑一笑"?"Fleabag":"Six Feet Under"):"The Wire"}</h3><p>{answers.length?(mood==="想笑一笑"?"倫敦生活":"六呎風雲"):"火線重案組 · 2002—2008"}</p><div className="hero-score-pair"><span><b>{answers.length?"92":"98"}%</b>契合度</span><span><b>{answers.length?(mood==="想笑一笑"?featured[10].score:featured[1].score):featured[0].score}</b>作品評分</span></div></div></section><section className="stats"><div><span>收錄作品</span><b>{shows.length}</b><small>都是已經完結的劇集</small></div><button className="stat-link" onClick={()=>setView("我的片單")}><span>你的片單</span><b>{saved.length}</b><small>看看你為下一個夜晚留下的片單　→</small></button><div><span>今晚情境</span><b className="mood-stat">{mood||"尚未選擇"}</b><small>{mood?"心情變了，也可以重新選擇":"完成探索後，推薦會更貼近此刻"}</small></div></section><section className="rec"><div className="panel-title"><div><small>為你而選 · {mood||"依長期品味"}</small><h2>時間沖刷不去的三部作品</h2></div><button onClick={()=>setView("排行榜")}>看看更多可能 →</button></div><div className="compact-grid three">{(mood==="想笑一笑"?[featured[10],featured[6],featured[1]]:mood==="想被安慰"?[featured[1],featured[10],featured[7]]:featured.slice(0,3)).map((s,i)=><article key={s.title} onClick={()=>setActive(s)}><div className="mini-cover" style={posters[s.title]?{backgroundImage:`linear-gradient(180deg,transparent,rgba(31,48,42,.7)),url(${posters[s.title]})`}:undefined}><span>0{i+1}</span><div className="cover-scores"><b>{personalScore(s)}%</b><small>契合度</small></div></div><div className="card-meta"><small>{s.genre} · {s.platform}</small><span>作品評分 {s.score}</span></div><h3>{imageQueryByTitle[s.title]}</h3><em>{s.title}</em><p>{s.note}</p><div className="match-reason">{i===0?"最符合你現在想看的心情":i===1?"同樣重視人物，情緒更內斂":"同樣有深度，節奏更緊湊"}</div></article>)}</div></section></>}
    {view==="排行榜"&&<section className="ranking"><div className="section-title"><div><span>FOR YOU · 100</span><h2>為你排序</h2><p>依「{answers.length?"思想考掘型":"尚未建立的品味"}」{mood&&<>與今晚「{mood}」</>}排列。契合度回答現在適不適合你；作品評分則回答它是否經得起時間。</p><div className="ranking-context"><span>觀看傾向：{answers.length?"思想考掘型":"尚未建立"}</span><span>今晚：{mood||"尚未選擇"}</span></div></div><button className="outline" onClick={()=>setWeightsOpen(!weightsOpen)}>微調我的品味</button></div>
      {weightsOpen&&<div className="preference-panel"><div className="preference-head"><div><h3>看影集時，你最在意什麼？</h3><p>憑直覺選就好。沒有標準答案，也可以隨時回來改變心意。</p></div><button onClick={()=>setAdvancedOpen(!advancedOpen)}>{advancedOpen?"簡單一點":"看看我們怎麼選"}</button></div><div className="preference-groups">{groupData.map((g,i)=><article key={g.name}><small>0{i+1}</small><h4>{g.name}</h4><p>{g.note}</p><div>{prefWords.map((word,n)=><button key={word} className={groupPrefs[i]===n+1?"active":""} onClick={()=>setGroupPrefs(v=>v.map((x,j)=>j===i?n+1:x))}>{word}</button>)}</div></article>)}</div>{advancedOpen&&<div className="advanced"><span>這份名單還參考了十個面向</span><p>{criteria.map((c,i)=><i key={c}>{c}<b>{weights[i]}%</b></i>)}</p><small>數字只是幫助我們保持一致；真正重要的，仍然是每部作品留下了什麼。</small></div>}</div>}
      <div className="tools"><div id="genres">{["全部","劇情","犯罪","喜劇","科幻","迷你影集"].map(g=><button className={genre===g?"active":""} onClick={()=>setGenre(g)} key={g}>{g}</button>)}</div><label>排序：<select value={sort} onChange={e=>setSort(e.target.value)}><option>契合度</option><option>作品評分</option><option>年份</option><option>平台</option></select></label></div>
      <div className="cards">{list.slice(0,showAll?list.length:12).map((s,i)=><article key={s.title} onClick={()=>setActive(s)}><div className="poster" style={posters[s.title]?{backgroundImage:`linear-gradient(180deg,transparent 35%,rgba(20,32,28,.88)),url(${posters[s.title]})`}:undefined}><span>{String(i+1).padStart(2,"0")}</span><div className="poster-score"><b>{personalScore(s)}%</b><small>契合度</small></div></div><div className="card-copy"><div className="card-meta"><small>{s.genre} · {s.platform} · {s.year}—{s.end}</small><span>作品評分 {s.score}</span></div><h3>{imageQueryByTitle[s.title]}</h3><em>{s.title}</em><p>{s.note}</p><div className="card-actions"><button className={saved.includes(s.title)?"saved-action":""} onClick={e=>{e.stopPropagation();toggleSaved(s)}}>{saved.includes(s.title)?"✓ 已在片單":"＋ 加入片單"}</button><button onClick={e=>{e.stopPropagation();toggleCompare(s)}}>{compare.some(x=>x.title===s.title)?"✓ 比較中":"⇄ 比較"}</button></div></div></article>)}</div><button className="more" onClick={()=>setShowAll(!showAll)}>{showAll?"收起作品":"瀏覽全部 " + list.length + " 部作品"}</button>
    </section>}
    {view==="我的片單"&&<section className="ranking"><div className="section-title"><div><span>MY LIST</span><h2>留給下一個晚上的故事</h2><p>收藏那些讓你有點心動、但還沒準備好立刻開始的作品。</p><div className="ranking-context"><span>觀看傾向：{answers.length?"思想考掘型":"尚未建立"}</span><span>今晚：{mood||"尚未選擇"}</span></div></div></div><div className="cards">{shows.filter(s=>saved.includes(s.title)).map(s=><article key={s.title} onClick={()=>setActive(s)}><div className="poster" style={posters[s.title]?{backgroundImage:`linear-gradient(180deg,transparent 35%,rgba(20,32,28,.88)),url(${posters[s.title]})`}:undefined}><div className="poster-score"><b>{personalScore(s)}%</b><small>契合度</small></div></div><div className="card-copy"><div className="card-meta"><small>{s.genre} · {s.platform}</small><span>作品評分 {s.score}</span></div><h3>{imageQueryByTitle[s.title]}</h3><em>{s.title}</em><p>{notes[s.title]?`「${notes[s.title]}」`:s.note}</p></div></article>)}</div></section>}
    {view==="評分方法"&&<section className="method method-deep"><div className="method-intro"><span>HOW WE READ</span><h2>我們不評哪部最好，<br/>而是哪部仍值得被重看。</h2><p>熱度會消退，技術會過時，觀眾也會改變。真正留下來的作品，往往不是毫無缺點，而是在多年之後，仍能讓人重新理解角色、時代，甚至自己。</p></div><div className="method-principles"><article><b>01</b><h3>結局也是作品的一部分</h3><p>我們只收錄已完結影集。因為一個故事如何承擔它曾經許下的承諾，必須等到最後一幕才能判斷。</p></article><article><b>02</b><h3>影響力不等於今天仍好看</h3><p>開創先例值得被記住，但歷史地位不能代替觀看經驗。我們同時追問：它曾經改變什麼？現在還能帶來什麼？</p></article><article><b>03</b><h3>缺點不會被平均掉</h3><p>有些缺陷會動搖整部作品，有些反而來自它的野心。分數不是把優缺點相加，而是判斷它們如何共同構成作品。</p></article></div><div className="evidence"><div><span>我們能確認的事</span><h3>事實層</h3><p>播出年份、完結狀態、評論趨勢、獎項、創作者影響，以及作品在後來影集中的可見痕跡。</p></div><div><span>我們必須承認的事</span><h3>判斷層</h3><p>人物是否成立、命題是否深刻、結局是否誠實、重看是否長出新意。這些無法假裝客觀，因此每一項都必須留下理由。</p></div></div><div className="criteria-block"><div><span>THE TEN LENSES</span><h3>十個觀看角度，不是十條真理。</h3><p>它們讓不同作品能被放在同一張桌上討論，也提醒我們：製作精良、令人上癮與真正重要，從來不是同一件事。</p></div><ol>{criteria.map((c,i)=><li key={c}><b>{String(i+1).padStart(2,"0")}</b><span>{c}</span></li>)}</ol></div><figure className="spirit-quote"><blockquote>“The great movies enlarge us, they civilize us, they make us more decent people.”</blockquote><p>偉大的作品拓展我們的生命經驗，也讓我們成為更理解他人的人。</p><figcaption>— Roger Ebert，<a href="https://www.rogerebert.com/roger-ebert/eberts-walk-of-fame-remarks" target="_blank" rel="noreferrer">Hollywood Walk of Fame Remarks</a>，2005</figcaption></figure></section>}
    </div>

    {compare.length>0&&<div className="comparebar"><span>比較作品（{compare.length}/3）</span>{compare.map(s=><button key={s.title} onClick={()=>toggleCompare(s)}>{imageQueryByTitle[s.title]} <small>{s.title}</small> ×</button>)}<button className="go" onClick={()=>setActive(compare[0])}>放在一起看看 →</button></div>}
    {active&&<div className="modal" onClick={()=>setActive(null)}><article className="detail" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setActive(null)}>×</button>{posters[active.title]&&<div className="full-poster" style={{backgroundImage:`url(${posters[active.title]})`}}/>}<div className="detail-copy"><small>{active.genre} · {active.platform} · {active.seasons}</small><h2>{imageQueryByTitle[active.title]}</h2><em>{active.title} · {active.year}—{active.end}</em><div className="detail-scores"><div><b>{personalScore(active)}%</b><span>與你的契合度</span><small>依觀看品味與今晚心情</small></div><div><b>{active.score}</b><span>作品評分</span><small>依十個觀看角度綜合判斷</small></div></div><h3>它為什麼值得留下？</h3><p>{active.note}</p><div className="scorelines">{criteria.slice(0,5).map((c,i)=><label key={c}>{c}<span><i style={{width:`${active.score-i*2}%`}}/></span><b>{active.score-i*2}</b></label>)}</div><button className={`primary save-primary ${saved.includes(active.title)?"is-saved":""}`} onClick={()=>toggleSaved(active)}>{saved.includes(active.title)?"✓ 已在我的片單 · 點擊移除":"＋ 留到我的片單"}</button><div className="personal-note"><div><h3>留一句話給自己</h3><small>看前的期待、看完的感受，或任何不想忘記的念頭。</small></div><textarea aria-label={`寫下關於 ${imageQueryByTitle[active.title]} 的心得`} maxLength={280} placeholder="例如：第二季之後，我開始用不同的眼光看待這個角色……" value={notes[active.title]||""} onChange={e=>updateNote(active.title,e.target.value)}/><span>{(notes[active.title]||"").length} / 280 · 自動保存在這台裝置</span></div></div></article></div>}
    {quizOpen&&<div className="quiz"><article><button className="close" onClick={()=>setQuizOpen(false)}>×</button>{quizPhase==="taste"?<><div className="quiz-progress"><span style={{width:`${((quiz+1)/quizData.length)*100}%`}}/></div><small>長期觀看品味 · {quiz+1} / {quizData.length}</small><h2>{quizData[quiz].q}</h2><p>沒有正確答案。請選擇第一個接近你直覺的回答。</p><div className="answers">{quizData[quiz].a.map((a,i)=><button key={a} onClick={()=>answerQuiz(a)}><b>{String.fromCharCode(65+i)}</b><span>{a}</span><i>→</i></button>)}</div></>:<><div className="quiz-progress complete"><span/></div><small>最後一題 · 此刻的你</small><h2>今晚，你想從一部影集得到什麼？</h2><p>這不會改變你的長期品味，只影響這一次的推薦。</p><div className="mood-grid">{["想笑一笑","想被安慰","想緊張刺激","想沉浸思考","給我一個意外"].map((m,i)=><button key={m} onClick={()=>chooseMood(m)}><b>0{i+1}</b><span>{m}</span><i>→</i></button>)}</div></>}<button className="skip" onClick={()=>setQuizOpen(false)}>稍後再回答</button></article></div>}{toast&&<div className="toast" role="status">{toast}</div>}
  </main>
}
