import { readFile, writeFile } from "node:fs/promises";

const source = await readFile(new URL("../app/data/shows.ts", import.meta.url), "utf8");
const shows = [...source.matchAll(/id:"([^"]+)",title:"([^"]+)",titleZh:"([^"]+)",years:"([^"]+)"/g)].map((match) => ({
  id: match[1],
  title: match[2],
  firstYear: Number(match[4].match(/\d{4}/)?.[0] ?? 0),
}));

const queryOverrides = {
  "battlestar-galactica": "Battlestar Galactica",
  "the-office-uk": "The Office",
  "life-on-mars-uk": "Life on Mars",
  "state-of-play-uk": "State of Play",
  "this-is-england-tv": "This Is England '86",
  "over-garden-wall": "Over the Garden Wall",
  "riget": "The Kingdom",
  "forbrydelsen": "Forbrydelsen",
  "les-revenants": "Les Revenants",
  "deutschland-trilogy": "Deutschland 83",
  "engrenages": "Engrenages",
  "money-heist": "La Casa de Papel",
  "gomorrah": "Gomorra",
  "romanzo-criminale": "Romanzo Criminale",
};

const normalize = (value) => value.normalize("NFKD").replace(/[^a-z0-9]+/gi, "").toLowerCase();
const wait = (milliseconds) => new Promise((resolve) => setTimeout(resolve, milliseconds));
const posterByShowId = {};
const localFallbacks = { "this-is-england-tv": "/posters/this-is-england-tv.svg" };
const review = [];

for (const [index, show] of shows.entries()) {
  const query = queryOverrides[show.id] ?? show.title;
  let response;
  for (let attempt = 0; attempt < 4; attempt += 1) {
    response = await fetch(`https://api.tvmaze.com/search/shows?q=${encodeURIComponent(query)}`);
    if (response.ok) break;
    if (response.status !== 429) throw new Error(`${show.id}: TVMaze returned ${response.status}`);
    await wait(1500 * (attempt + 1));
  }
  if (!response?.ok) throw new Error(`${show.id}: TVMaze rate limit did not recover`);

  const results = await response.json();
  const target = normalize(queryOverrides[show.id] ?? show.title.split("／")[0]);
  const candidates = results
    .filter(({ show: candidate }) => candidate.image?.original || candidate.image?.medium)
    .map(({ show: candidate }) => {
      const candidateTitle = normalize(candidate.name);
      const candidateYear = Number(candidate.premiered?.slice(0, 4) ?? 0);
      const titleScore = candidateTitle === target ? 100 : candidateTitle.includes(target) || target.includes(candidateTitle) ? 45 : 0;
      const yearScore = candidateYear === show.firstYear ? 40 : Math.abs(candidateYear - show.firstYear) <= 2 ? 10 : 0;
      return { candidate, score: titleScore + yearScore };
    })
    .sort((a, b) => b.score - a.score);

  const best = candidates[0];
  if (!best && localFallbacks[show.id]) {
    posterByShowId[show.id] = localFallbacks[show.id];
  } else if (!best) {
    review.push(`${show.id}: no poster found (query: ${query})`);
  } else {
    posterByShowId[show.id] = best.candidate.image.original || best.candidate.image.medium;
    if (best.score < 100) review.push(`${show.id}: ${best.candidate.name} (${best.candidate.premiered ?? "unknown"}), confidence ${best.score}`);
  }
  if ((index + 1) % 20 === 0) process.stdout.write(`resolved ${index + 1}/${shows.length}\n`);
  await wait(550);
}

const rows = Object.entries(posterByShowId).map(([id, url]) => `  "${id}": "${url}",`).join("\n");
await writeFile(new URL("../app/data/posters.ts", import.meta.url), `// Generated by scripts/resolve-posters.mjs; review before committing.\nexport const posterByShowId: Record<string, string> = {\n${rows}\n};\n`);
console.log(`resolved ${Object.keys(posterByShowId).length}/${shows.length}`);
if (review.length) console.log(`needs review:\n${review.join("\n")}`);
